### ISSUE TITLE
Can you give a Dockerfile?

### ISSUE THREAD

**Issue by zjuchenyuan** [zjlywjh001/PhrackCTF-Platform-Personal#1]
Docker is a good choice for easy distribution and deployment.

I'm not familiar with Java or mvn, but I just want to deploy this project and have a try with it.

So, can you provide a Dockerfile? Thanks a lot!

**Comment by zjlywjh001** [comment]
docker image is available now.
See here: https://github.com/zjlywjh001/phrackCTF-Personal-Docker
